figure(1)
surface(regeig(:,:,1))
surface(regeig(:,:,2))
surface(regeig(:,:,3))
%surface(regeig(:,:,4)./max(max(regeig(:,:,4))))
%surface(regeig(:,:,5)./max(max(regeig(:,:,5))))
%surface(regeig(:,:,6)./max(max(regeig(:,:,6))))